(define (problem BLOCKS)
  (:domain BLOCKS)
  (:objects E D B A C - block)
  (:init 
    (CLEAR C) 
    (CLEAR A) 
    (CLEAR B) 
    (CLEAR D) 
    (CLEAR E) 
    (ONTABLE C) 
    (ONTABLE A) 
    (ONTABLE B) 
    (ONTABLE D) 
    (ONTABLE E) 
    (HANDEMPTY)
  )
  (:goal (and (ON E D) (ON D C) (ON C B) (ON B A)))
)